### FAQ 등록
POST http://backoffice.conects.com/api/faqs
Content-Type: application/json

{
  "faqs": [
    {
      "question": "3기 선발 기준은 어떻게 되나요?",
      "answer": "구성원에게 기술적 영감을 줄 수 있는가, 구성원들을 어울리게 만드는데 기여할 수 있는가의 두가지 관점에서, 구성원들의 성장에 긍정적인 영향을 끼칠 수 있는 사람을 선호합니다."
    }
  ]
}